const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST'
const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS'
const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE'
const UNIVERSAL_ERROR = 'UNIVERSAL_ERROR'
const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
const PROFILE_SUCCESS = 'PROFILE_SUCCESS'
const GET_LIST_ITINERARY_SUCCESS = "GET_LIST_ITINERARY_SUCCESS"
const POST_ITINERARY_SUCCESS = 'POST_ITINERARY_SUCCESS'
const GET_ACTIVITIES_SUCCESS = "GET_ACTIVITIES_SUCCESS"
const ADD_POST_ITINERARY_SUCCESS = "ADD_POST_ITINERARY_SUCCESS"
const GET_PUBLIC_POST_SUCCESS = "GET_PUBLIC_POST_SUCCESS"
const SUCCESS_FETCH_ADDED_POST = "SUCCESS_FETCH_ADDED_POST"
const SUCCESS_ADD_POST_BY_BOT = "SUCCESS_ADD_POST_BY_BOT"
const SET_LOADING = "SET_LOADING"
const ADD_LOCATION_SUCCESS = "ADD_LOCATION_SUCCESS"
const USER_ID_SUCCESS = "USER_ID_SUCCESS"

export { FETCH_DATA_REQUEST, GET_ACTIVITIES_SUCCESS, FETCH_DATA_SUCCESS, FETCH_DATA_FAILURE, LOGIN_SUCCESS, UNIVERSAL_ERROR, PROFILE_SUCCESS, POST_ITINERARY_SUCCESS, GET_LIST_ITINERARY_SUCCESS, ADD_POST_ITINERARY_SUCCESS, GET_PUBLIC_POST_SUCCESS, SUCCESS_FETCH_ADDED_POST, SUCCESS_ADD_POST_BY_BOT, SET_LOADING, ADD_LOCATION_SUCCESS, USER_ID_SUCCESS } 